// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts

import { Livro } from '../livro';
import { Component, OnInit } from '@angular/core';

import { ControleLivros} from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  livros: Livro[] = [];

  constructor(private ControleLivros: ControleLivros) { }

  ngOnInit() {
    this.ControleLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir(codigo: string) {
    this.ControleLivros.excluir(codigo).then(() => {
      return this.ControleLivros.obterLivros();
    }).then((livros) => {
      this.livros = livros;
    });
  }
}

<main>
    <h2>Catálogo de Livros</h2>
  
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Título</th>
          <th scope="col">Resumo</th>
          <th scope="col">Editora</th>
          <th scope="col">Autores</th>  
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.titulo }} <div><br></div>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
            </button></td>
          
          <td class="w-50 p-2">{{ livro.resumo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
  <style>
    main{
      margin: auto;
      width: 70%;
    }
    h2{
      font-size: 70px;
    }
  </style>

// clientes/livros-next/src/pages/LivroLista.tsx
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Menu from '../../componentes/Menu';
import { NextPage } from 'next';
import React from 'react';

const baseURL = "http://localhost:3000/api/livros";

const obter = async () => {
  const resposta = await fetch(baseURL);
  return resposta.json();
};

const excluirLivro = async (codigo: number) => {
  const resposta = await fetch(baseURL, {
    method: 'DELETE',    
  });
  return resposta.ok;
};

const LivroLista:NextPage = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    if (!carregado) {
      obter().then((dados) => {
        setLivros(dados);
        setCarregado(true);
      });
    }
  }, [carregado]);

  const excluir = async (codigo: number) => {
    const excluidoComSucesso = await excluirLivro(codigo);
    if (excluidoComSucesso) {
      const livrosAtualizados = livros.filter((livro: any) => livro.codigo !== codigo);
      setLivros(livrosAtualizados);
    }
  };
  
  return (
    <div>
      <Head>
        <title>Livro Lista</title>
      </Head>
      <Menu />
      <main className="container">
        <h1>Catálogo de Livros</h1>
        <table className="table table-striped">
          <thead className=".bg-dark">
            <tr>
              <th className="p-3 mb-2 bg-dark text-white">Título</th>
              <th className="w-50  mb-2 bg-dark text-white p-3">Resumo</th>
              <th className="p-3 mb-2 bg-dark text-white">Autor</th>
              <th className="p-3 mb-2 bg-dark text-white">Editora</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((LivroMongo: any) => (
              <tr key={LivroMongo.codigo}>
                <td>{LivroMongo.titulo} <br/>
                <button
                  type="button"
                  className="btn btn-danger"
                  onClick={() => excluir(LivroMongo.codigo)}>Excluir</button>

                  </td>
                <td>{LivroMongo.resumo}</td>
                <td>{LivroMongo.autor}</td>
                <td>{LivroMongo.editora}</td>
                <td>
                  
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;
